#def rlen(X): return range(len(X))
rlen = lambda x: range(len(x))
#def write(X): return ' '.join([str(x) for x in X])
write = lambda x: ' '.join([str(x) for x in X])
#def vec(X): return np.array(X)
vec = lambda x: np.array(X)
#def vlen(v): return np.sqrt(np.dot(v,v))
vlen = lambda v: np.sqrt(np.dot(v,v))
#def ran_mat(low,high,size): return np.random.randint(low,high,size=size)
ran_mat = lambda low, high, size: np.random.randint(low,high,size=size)
